global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Load alert rules
rule_files:
  - "rules/ml_alerts.yml"

scrape_configs:
  - job_name: 'flask_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:5002']


  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  # Prometheus scraping itself

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']  # Grafana container name (optional)
